version: '2'

services:
  web_app:
    image: bluepandatech/sensemirrorengine_web_app:latest
    ports:
      - 8000:8000
    volumes:
      - /home/pi/media:/web_app/static/media
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: bluepandatech/sensemirrorengine_nginx:latest
    ports:
      - 80:80
    volumes:
      - /home/pi/media:/opt/static/media
    depends_on:
      - web_app
    restart: unless-stopped

  postgres:
    image: arm32v7/postgres:11.1
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=cime
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  ui:
    image: bluepandatech/sensemirrorengine_ui:latest
    privileged: true
    volumes:
      - /home/pi/media:/ui/assets
    depends_on:
      - web_app
    network_mode: "host"
    restart: unless-stopped
  
  watchtower:
    image: v2tec/watchtower:armhf-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  pgdata: {}
