version: '2'

services:
  web_app:
    build:
      context: ./web_app/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./web_app/web_app:/web_app
      - /home/pi/media:/web_app/static/media
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - /home/pi/media:/opt/static/media
    depends_on:
      - web_app

  postgres:
    image: arm32v7/postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=cime
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  ui:
    build:
      context: ./ui/
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /home/pi/media:/ui/assets
    depends_on:
      - web_app
    network_mode: "host"

volumes:
  pgdata: {}
